import i18n from 'i18next';
import { initReactI18next } from 'react-i18next';
import LanguageDetector from 'i18next-browser-languagedetector';

import ptTranslations from './locales/pt.json';
import enTranslations from './locales/en.json';
import frTranslations from './locales/fr.json';

const resources = {
  pt: { translation: ptTranslations },
  en: { translation: enTranslations },
  fr: { translation: frTranslations },
};

// Language codes for document generation
export const DOCUMENT_LANGUAGES = {
  pt: { code: 'pt', label: 'Português', locale: 'pt-AO' },
  en: { code: 'en', label: 'English', locale: 'en-US' },
  fr: { code: 'fr', label: 'Français', locale: 'fr-FR' },
} as const;

export type DocumentLanguageCode = keyof typeof DOCUMENT_LANGUAGES;

// Document translations for reports
export const documentTranslations = {
  pt: {
    coverTitle: 'RELATÓRIO ANALÍTICO',
    infoPage: 'PÁGINA INFORMATIVA',
    dataSources: 'FONTES DE DADOS',
    generatedBy: 'Gerado por',
    confidential: 'CONFIDENCIAL - USO INTERNO',
    page: 'Página',
    of: 'de',
    executiveSummary: 'Sumário Executivo',
    mainHighlights: 'Destaques Principais',
    disclaimer: 'AVISO LEGAL: Este relatório foi gerado pela AlphaData - Inteligência de Mercado Petrolífero Angolano. As informações aqui contidas são para fins informativos e não constituem aconselhamento financeiro ou de investimento.',
    production: 'Produção',
    market: 'Mercado',
    exports: 'Exportações',
    risk: 'Riscos',
    general: 'Geral',
    operator: 'Operador',
    block: 'Bloco',
    field: 'Campo',
    status: 'Status',
    price: 'Preço',
    variation: 'Variação',
    date: 'Data',
    destination: 'Destino',
    volume: 'Volume',
    tanker: 'Tanque',
    crudeType: 'Tipo de Crude',
    aiGenerated: 'Gerado com IA',
    officialSources: 'Fontes Oficiais',
    sourcesList: ['BPEP - Bureau de Programação Económica e Planificação', 'ANP - Agência Nacional do Petróleo', 'MIREMPET - Ministério dos Recursos Minerais', 'OPEP - Organização dos Países Exportadores de Petróleo', 'APIs de Mercado em Tempo Real'],
    // PDF-specific labels
    generatedAt: 'Gerado em',
    report: 'Relatório',
    visualAnalysis: 'Análise Visual',
    productionByOperator: 'Produção por Operador',
    marketShareProduction: 'Quota de Mercado (Produção)',
    priceEvolution: 'Evolução de Preços (USD/bbl)',
    pricesByType: 'Preços por Tipo de Crude (USD/bbl)',
    exportsByDestination: 'Exportações por Destino',
    productionData: 'Dados de Produção',
    priceTable: 'Tabela de Preços',
    exportTable: 'Tabela de Exportações',
    productionBpd: 'Produção (bpd)',
    priceUsd: 'Preço (USD)',
    footerText: 'AlphaData - Inteligência de Mercado Petrolífero Angolano',
    period: 'Período',
    notAvailable: 'N/D',
    // DOCX
    docxPeriod: 'Período',
    docxGeneratedAt: 'Gerado em',
    // Type names
    typeProduction: 'Produção',
    typeMarket: 'Mercado',
    typeExports: 'Exportações',
    typeRisk: 'Risco',
    typePredictions: 'Previsões',
    typeGeneral: 'Geral',
    typeReport: 'Relatório',
  },
  en: {
    coverTitle: 'ANALYTICAL REPORT',
    infoPage: 'INFORMATION PAGE',
    dataSources: 'DATA SOURCES',
    generatedBy: 'Generated by',
    confidential: 'CONFIDENTIAL - INTERNAL USE',
    page: 'Page',
    of: 'of',
    executiveSummary: 'Executive Summary',
    mainHighlights: 'Main Highlights',
    disclaimer: 'LEGAL NOTICE: This report was generated by AlphaData - Angolan Oil Market Intelligence. The information contained herein is for informational purposes only and does not constitute financial or investment advice.',
    production: 'Production',
    market: 'Market',
    exports: 'Exports',
    risk: 'Risks',
    general: 'General',
    operator: 'Operator',
    block: 'Block',
    field: 'Field',
    status: 'Status',
    price: 'Price',
    variation: 'Variation',
    date: 'Date',
    destination: 'Destination',
    volume: 'Volume',
    tanker: 'Tanker',
    crudeType: 'Crude Type',
    aiGenerated: 'AI Generated',
    officialSources: 'Official Sources',
    sourcesList: ['BPEP - Economic Planning and Programming Bureau', 'ANP - National Petroleum Agency', 'MIREMPET - Ministry of Mineral Resources', 'OPEC - Organization of the Petroleum Exporting Countries', 'Real-Time Market APIs'],
    // PDF-specific labels
    generatedAt: 'Generated on',
    report: 'Report',
    visualAnalysis: 'Visual Analysis',
    productionByOperator: 'Production by Operator',
    marketShareProduction: 'Market Share (Production)',
    priceEvolution: 'Price Evolution (USD/bbl)',
    pricesByType: 'Prices by Crude Type (USD/bbl)',
    exportsByDestination: 'Exports by Destination',
    productionData: 'Production Data',
    priceTable: 'Price Table',
    exportTable: 'Export Table',
    productionBpd: 'Production (bpd)',
    priceUsd: 'Price (USD)',
    footerText: 'AlphaData - Angolan Oil Market Intelligence',
    period: 'Period',
    notAvailable: 'N/A',
    // DOCX
    docxPeriod: 'Period',
    docxGeneratedAt: 'Generated on',
    // Type names
    typeProduction: 'Production',
    typeMarket: 'Market',
    typeExports: 'Exports',
    typeRisk: 'Risk',
    typePredictions: 'Predictions',
    typeGeneral: 'General',
    typeReport: 'Report',
  },
  fr: {
    coverTitle: 'RAPPORT ANALYTIQUE',
    infoPage: 'PAGE D\'INFORMATION',
    dataSources: 'SOURCES DE DONNÉES',
    generatedBy: 'Généré par',
    confidential: 'CONFIDENTIEL - USAGE INTERNE',
    page: 'Page',
    of: 'de',
    executiveSummary: 'Résumé Exécutif',
    mainHighlights: 'Points Clés',
    disclaimer: 'AVIS JURIDIQUE: Ce rapport a été généré par AlphaData - Intelligence du Marché Pétrolier Angolais. Les informations contenues sont à titre informatif uniquement et ne constituent pas un conseil financier ou d\'investissement.',
    production: 'Production',
    market: 'Marché',
    exports: 'Exportations',
    risk: 'Risques',
    general: 'Général',
    operator: 'Opérateur',
    block: 'Bloc',
    field: 'Champ',
    status: 'Statut',
    price: 'Prix',
    variation: 'Variation',
    date: 'Date',
    destination: 'Destination',
    volume: 'Volume',
    tanker: 'Pétrolier',
    crudeType: 'Type de Brut',
    aiGenerated: 'Généré par IA',
    officialSources: 'Sources Officielles',
    sourcesList: ['BPEP - Bureau de Programmation Économique', 'ANP - Agence Nationale du Pétrole', 'MIREMPET - Ministère des Ressources Minérales', 'OPEP - Organisation des Pays Exportateurs de Pétrole', 'APIs de Marché en Temps Réel'],
    // PDF-specific labels
    generatedAt: 'Généré le',
    report: 'Rapport',
    visualAnalysis: 'Analyse Visuelle',
    productionByOperator: 'Production par Opérateur',
    marketShareProduction: 'Part de Marché (Production)',
    priceEvolution: 'Évolution des Prix (USD/bbl)',
    pricesByType: 'Prix par Type de Brut (USD/bbl)',
    exportsByDestination: 'Exportations par Destination',
    productionData: 'Données de Production',
    priceTable: 'Tableau des Prix',
    exportTable: 'Tableau des Exportations',
    productionBpd: 'Production (bpd)',
    priceUsd: 'Prix (USD)',
    footerText: 'AlphaData - Intelligence du Marché Pétrolier Angolais',
    period: 'Période',
    notAvailable: 'N/D',
    // DOCX
    docxPeriod: 'Période',
    docxGeneratedAt: 'Généré le',
    // Type names
    typeProduction: 'Production',
    typeMarket: 'Marché',
    typeExports: 'Exportations',
    typeRisk: 'Risque',
    typePredictions: 'Prévisions',
    typeGeneral: 'Général',
    typeReport: 'Rapport',
  },
};

export const getDocumentTranslation = (lang: DocumentLanguageCode) => {
  return documentTranslations[lang] || documentTranslations.pt;
};

i18n
  .use(LanguageDetector)
  .use(initReactI18next)
  .init({
    resources,
    fallbackLng: 'pt',
    supportedLngs: ['pt', 'en', 'fr'],
    detection: {
      // Priority: localStorage, then browser language, then html tag
      order: ['localStorage', 'navigator', 'htmlTag'],
      caches: ['localStorage'],
      lookupLocalStorage: 'alphadata-language',
      // Also check browser's Accept-Language header
      lookupFromPathIndex: 0,
      lookupFromSubdomainIndex: 0,
    },
    interpolation: {
      escapeValue: false,
    },
    react: {
      useSuspense: false,
    },
  });

export default i18n;
