/**
 * Full report translations for PT / EN / FR
 * Used by PDF, DOCX, and Excel report generators.
 */

export type ReportLang = 'pt' | 'en' | 'fr';

export interface ReportTranslation {
  coverLabel: string;
  reportType: string;
  generatedBy: string;
  generatedOn: string;
  period: string;
  type: string;
  confidential: string;
  internalUse: string;
  pageOf: (x: number, y: number) => string;
  companySection: string;
  countryInfo: string;
  country: string;
  region: string;
  currency: string;
  timezone: string;
  execSummary: string;
  keyMetrics: string;
  visualAnalysis: string;
  priceEvolution: string;
  priceTable: string;
  crudeType: string;
  price: string;
  change: string;
  date: string;
  basin: string;
  benchmark: string;
  highlights: string;
  recommendations: string;
  dataSources: string;
  dataQuality: string;
  dataQualityText: string;
  legalNotice: string;
  legalText: string;
  allRights: string;
  autoGenerated: string;
  priority: string;
  impact: string;
  timeline: string;
  high: string;
  medium: string;
  low: string;
  shortTerm: string;
  mediumTerm: string;
  longTerm: string;
  critical: string;
  warning: string;
  info: string;
  positive: string;
  official: string;
  regulator: string;
  governmental: string;
  market: string;
  ai: string;
  lastUpdated: string;
  source: string;
  dataSource1Name: string;
  dataSource1Desc: string;
  dataSource2Name: string;
  dataSource2Desc: string;
  dataSource3Name: string;
  dataSource3Desc: string;
  dataSource4Name: string;
  dataSource4Desc: string;
  languageBadge: string;
  // Extra labels used in document generators
  operator: string;
  block: string;
  field: string;
  status: string;
  productionBpd: string;
  priceUsd: string;
  variation: string;
  destination: string;
  volume: string;
  tanker: string;
  productionByOperator: string;
  marketShareProduction: string;
  pricesByType: string;
  exportsByDestination: string;
  productionData: string;
  exportTable: string;
  footerText: string;
  notAvailable: string;
  report: string;
  // Type names
  typeProduction: string;
  typeMarket: string;
  typeExports: string;
  typeRisk: string;
  typePredictions: string;
  typeGeneral: string;
  typeReport: string;
  // Cover page labels
  intelligence: string;
  aiBadge: string;
  liveData: string;
  requestingCompany: string;
  requestedBy: string;
  company: string;
  nif: string;
  sector: string;
  name: string;
  role: string;
  email: string;
  confidentialNotice: string;
  dataSourcesTitle: string;
  dataSourcesIntro: string;
  reportInfo: string;
  titleLabel: string;
  method: string;
  aiMethod: string;
  // Excel
  description: string;
  contact: string;
  website: string;
  address: string;
  endInfoPage: string;
}

export const reportTranslations: Record<ReportLang, ReportTranslation> = {
  pt: {
    coverLabel: 'RELATORIO ALPHADATA',
    reportType: 'Analise de Mercado & Precos',
    generatedBy: 'Gerado por IA',
    generatedOn: 'Gerado em',
    period: 'Periodo',
    type: 'Tipo',
    confidential: 'CONFIDENCIAL',
    internalUse: 'USO INTERNO',
    pageOf: (x, y) => `Pagina ${x} de ${y}`,
    companySection: 'ENTIDADE GERADORA',
    countryInfo: 'INFORMACOES DO PAIS',
    country: 'Pais:',
    region: 'Regiao:',
    currency: 'Moeda:',
    timezone: 'Fuso Horario:',
    execSummary: 'RESUMO EXECUTIVO',
    keyMetrics: 'METRICAS-CHAVE',
    visualAnalysis: 'ANALISE VISUAL',
    priceEvolution: 'Evolucao dos Precos (USD/bbl)',
    priceTable: 'TABELA DE PRECOS',
    crudeType: 'Tipo de Crude',
    price: 'Preco (USD/bbl)',
    change: 'Variacao',
    date: 'Data',
    basin: 'Bacia',
    benchmark: 'REFERENCIA',
    highlights: 'DESTAQUES E ALERTAS',
    recommendations: 'RECOMENDACOES ESTRATEGICAS',
    dataSources: 'FONTES DE DADOS',
    dataQuality: 'NOTA SOBRE QUALIDADE DOS DADOS',
    dataQualityText: 'Todas as fontes sao verificadas e regularmente actualizadas para garantir a precisao e fiabilidade das analises.',
    legalNotice: 'AVISO LEGAL',
    legalText: 'Este relatorio foi gerado pela AlphaData. As informacoes contidas sao de caracter informativo e nao constituem aconselhamento financeiro ou de investimento.',
    allRights: 'Todos os direitos reservados',
    autoGenerated: 'Gerado automaticamente por IA',
    priority: 'Prioridade',
    impact: 'Impacto',
    timeline: 'Prazo',
    high: 'Alto',
    medium: 'Medio',
    low: 'Baixo',
    shortTerm: 'Curto prazo',
    mediumTerm: 'Medio prazo',
    longTerm: 'Longo prazo',
    critical: 'CRITICO',
    warning: 'ATENCAO',
    info: 'INFO',
    positive: 'POSITIVO',
    official: 'Oficial',
    regulator: 'Regulador',
    governmental: 'Governamental',
    market: 'Mercado',
    ai: 'IA',
    lastUpdated: 'Actualizado',
    source: 'Fonte',
    dataSource1Name: 'ANPG - Agencia Nacional de Petroleo e Gas',
    dataSource1Desc: 'Dados oficiais de producao e exportacao do sector petrolifero angolano',
    dataSource2Name: 'Ministerio dos Recursos Minerais e Petroleo',
    dataSource2Desc: 'Politicas e directrizes do sector energetico',
    dataSource3Name: 'APIs de Mercado Internacional',
    dataSource3Desc: 'Cotacoes Brent, WTI e contratos a prazo em tempo real',
    dataSource4Name: 'AlphaData AI Engine',
    dataSource4Desc: 'Modelos proprietarios de previsao e analise de tendencias',
    languageBadge: 'Portugues',
    // Document labels
    operator: 'Operador',
    block: 'Bloco',
    field: 'Campo',
    status: 'Status',
    productionBpd: 'Producao (bpd)',
    priceUsd: 'Preco (USD)',
    variation: 'Variacao',
    destination: 'Destino',
    volume: 'Volume',
    tanker: 'Tanque',
    productionByOperator: 'Producao por Operador',
    marketShareProduction: 'Quota de Mercado (Producao)',
    pricesByType: 'Precos por Tipo de Crude (USD/bbl)',
    exportsByDestination: 'Exportacoes por Destino',
    productionData: 'Dados de Producao',
    exportTable: 'Tabela de Exportacoes',
    footerText: 'AlphaData - Inteligencia de Mercado Petrolifero Angolano',
    notAvailable: 'N/D',
    report: 'Relatorio',
    typeProduction: 'Producao',
    typeMarket: 'Mercado',
    typeExports: 'Exportacoes',
    typeRisk: 'Risco',
    typePredictions: 'Previsoes',
    typeGeneral: 'Geral',
    typeReport: 'Relatorio',
    // Cover page
    intelligence: 'INTELIGENCIA DO MERCADO PETROLIFERO',
    aiBadge: 'GERADO POR IA',
    liveData: 'DADOS EM TEMPO REAL',
    requestingCompany: 'EMPRESA SOLICITANTE',
    requestedBy: 'SOLICITADO POR',
    company: 'Empresa:',
    nif: 'NIF:',
    sector: 'Sector:',
    name: 'Nome:',
    role: 'Cargo:',
    email: 'Email:',
    confidentialNotice: 'Este documento contem informacoes confidenciais. A sua distribuicao esta restrita a destinatarios autorizados.',
    dataSourcesTitle: 'Fontes de Dados e Referencias',
    dataSourcesIntro: 'Este relatorio baseia-se em multiplas fontes de dados verificadas e confiaveis para garantir a precisao e integridade das analises apresentadas.',
    reportInfo: 'INFORMACOES DO RELATORIO',
    titleLabel: 'Titulo:',
    method: 'Metodo:',
    aiMethod: 'Gerado com Inteligencia Artificial',
    description: 'Descricao:',
    contact: 'Contacto:',
    website: 'Website:',
    address: 'Endereco:',
    endInfoPage: 'FIM DA PAGINA INFORMATIVA - INICIO DO CONTEUDO DO RELATORIO',
  },
  en: {
    coverLabel: 'ALPHADATA REPORT',
    reportType: 'Market & Price Analysis',
    generatedBy: 'AI Generated',
    generatedOn: 'Generated on',
    period: 'Period',
    type: 'Type',
    confidential: 'CONFIDENTIAL',
    internalUse: 'INTERNAL USE',
    pageOf: (x, y) => `Page ${x} of ${y}`,
    companySection: 'ISSUING COMPANY',
    countryInfo: 'COUNTRY INFORMATION',
    country: 'Country:',
    region: 'Region:',
    currency: 'Currency:',
    timezone: 'Timezone:',
    execSummary: 'EXECUTIVE SUMMARY',
    keyMetrics: 'KEY METRICS',
    visualAnalysis: 'VISUAL ANALYSIS',
    priceEvolution: 'Price Evolution (USD/bbl)',
    priceTable: 'PRICE TABLE',
    crudeType: 'Crude Type',
    price: 'Price (USD/bbl)',
    change: 'Change',
    date: 'Date',
    basin: 'Basin',
    benchmark: 'BENCHMARK',
    highlights: 'HIGHLIGHTS & ALERTS',
    recommendations: 'STRATEGIC RECOMMENDATIONS',
    dataSources: 'DATA SOURCES',
    dataQuality: 'DATA QUALITY NOTE',
    dataQualityText: 'All data sources are verified and regularly updated to ensure the accuracy and reliability of analyses.',
    legalNotice: 'LEGAL NOTICE',
    legalText: 'This report was generated by AlphaData. The information contained herein is for informational purposes only and does not constitute financial or investment advice.',
    allRights: 'All rights reserved',
    autoGenerated: 'Automatically generated by AI',
    priority: 'Priority',
    impact: 'Impact',
    timeline: 'Timeline',
    high: 'High',
    medium: 'Medium',
    low: 'Low',
    shortTerm: 'Short term',
    mediumTerm: 'Medium term',
    longTerm: 'Long term',
    critical: 'CRITICAL',
    warning: 'WARNING',
    info: 'INFO',
    positive: 'POSITIVE',
    official: 'Official',
    regulator: 'Regulator',
    governmental: 'Governmental',
    market: 'Market',
    ai: 'AI',
    lastUpdated: 'Updated',
    source: 'Source',
    dataSource1Name: 'ANPG - National Oil & Gas Agency',
    dataSource1Desc: 'Official production and export data for Angola\'s petroleum sector',
    dataSource2Name: 'Ministry of Mineral Resources and Petroleum',
    dataSource2Desc: 'Energy sector policies and regulatory guidelines',
    dataSource3Name: 'International Market APIs',
    dataSource3Desc: 'Real-time Brent, WTI and futures contract pricing',
    dataSource4Name: 'AlphaData AI Engine',
    dataSource4Desc: 'Proprietary forecasting and trend analysis models',
    languageBadge: 'English',
    // Document labels
    operator: 'Operator',
    block: 'Block',
    field: 'Field',
    status: 'Status',
    productionBpd: 'Production (bpd)',
    priceUsd: 'Price (USD)',
    variation: 'Variation',
    destination: 'Destination',
    volume: 'Volume',
    tanker: 'Tanker',
    productionByOperator: 'Production by Operator',
    marketShareProduction: 'Market Share (Production)',
    pricesByType: 'Prices by Crude Type (USD/bbl)',
    exportsByDestination: 'Exports by Destination',
    productionData: 'Production Data',
    exportTable: 'Export Table',
    footerText: 'AlphaData - Angolan Oil Market Intelligence',
    notAvailable: 'N/A',
    report: 'Report',
    typeProduction: 'Production',
    typeMarket: 'Market',
    typeExports: 'Exports',
    typeRisk: 'Risk',
    typePredictions: 'Predictions',
    typeGeneral: 'General',
    typeReport: 'Report',
    // Cover page
    intelligence: 'OIL MARKET INTELLIGENCE',
    aiBadge: 'AI GENERATED',
    liveData: 'REAL-TIME DATA',
    requestingCompany: 'REQUESTING COMPANY',
    requestedBy: 'REQUESTED BY',
    company: 'Company:',
    nif: 'Tax ID:',
    sector: 'Sector:',
    name: 'Name:',
    role: 'Role:',
    email: 'Email:',
    confidentialNotice: 'This document contains confidential information. Distribution is restricted to authorised recipients.',
    dataSourcesTitle: 'Data Sources and References',
    dataSourcesIntro: 'This report is based on multiple verified and reliable data sources to ensure the accuracy and integrity of the analyses presented.',
    reportInfo: 'REPORT INFORMATION',
    titleLabel: 'Title:',
    method: 'Method:',
    aiMethod: 'Generated with Artificial Intelligence',
    description: 'Description:',
    contact: 'Contact:',
    website: 'Website:',
    address: 'Address:',
    endInfoPage: 'END OF INFORMATION PAGE - START OF REPORT CONTENT',
  },
  fr: {
    coverLabel: 'RAPPORT ALPHADATA',
    reportType: 'Analyse du Marche & des Prix',
    generatedBy: 'Genere par IA',
    generatedOn: 'Genere le',
    period: 'Periode',
    type: 'Type',
    confidential: 'CONFIDENTIEL',
    internalUse: 'USAGE INTERNE',
    pageOf: (x, y) => `Page ${x} de ${y}`,
    companySection: 'SOCIETE GENERATRICE',
    countryInfo: 'INFORMATIONS SUR LE PAYS',
    country: 'Pays:',
    region: 'Region:',
    currency: 'Monnaie:',
    timezone: 'Fuseau Horaire:',
    execSummary: 'RESUME EXECUTIF',
    keyMetrics: 'METRIQUES CLES',
    visualAnalysis: 'ANALYSE VISUELLE',
    priceEvolution: 'Evolution des Prix (USD/bbl)',
    priceTable: 'TABLEAU DES PRIX',
    crudeType: 'Type de Brut',
    price: 'Prix (USD/bbl)',
    change: 'Variation',
    date: 'Date',
    basin: 'Bassin',
    benchmark: 'REFERENCE',
    highlights: 'POINTS SAILLANTS & ALERTES',
    recommendations: 'RECOMMANDATIONS STRATEGIQUES',
    dataSources: 'SOURCES DE DONNEES',
    dataQuality: 'NOTE SUR LA QUALITE DES DONNEES',
    dataQualityText: 'Toutes les sources de donnees sont verifiees et regulierement mises a jour pour garantir la precision et la fiabilite des analyses.',
    legalNotice: 'AVIS JURIDIQUE',
    legalText: 'Ce rapport a ete genere par AlphaData. Les informations contenues sont a titre informatif uniquement et ne constituent pas un conseil financier ou d\'investissement.',
    allRights: 'Tous droits reserves',
    autoGenerated: 'Genere automatiquement par IA',
    priority: 'Priorite',
    impact: 'Impact',
    timeline: 'Delai',
    high: 'Eleve',
    medium: 'Moyen',
    low: 'Faible',
    shortTerm: 'Court terme',
    mediumTerm: 'Moyen terme',
    longTerm: 'Long terme',
    critical: 'CRITIQUE',
    warning: 'ATTENTION',
    info: 'INFO',
    positive: 'POSITIF',
    official: 'Officiel',
    regulator: 'Regulateur',
    governmental: 'Gouvernemental',
    market: 'Marche',
    ai: 'IA',
    lastUpdated: 'Mis a jour',
    source: 'Source',
    dataSource1Name: 'ANPG - Agence Nationale du Petrole et du Gaz',
    dataSource1Desc: 'Donnees officielles de production et d\'exportation du secteur petrolier angolais',
    dataSource2Name: 'Ministere des Ressources Minerales et du Petrole',
    dataSource2Desc: 'Politiques et directives du secteur energetique',
    dataSource3Name: 'APIs de Marche International',
    dataSource3Desc: 'Cotations Brent, WTI et contrats a terme en temps reel',
    dataSource4Name: 'AlphaData AI Engine',
    dataSource4Desc: 'Modeles proprietaires de prevision et d\'analyse de tendances',
    languageBadge: 'Francais',
    // Document labels
    operator: 'Operateur',
    block: 'Bloc',
    field: 'Champ',
    status: 'Statut',
    productionBpd: 'Production (bpd)',
    priceUsd: 'Prix (USD)',
    variation: 'Variation',
    destination: 'Destination',
    volume: 'Volume',
    tanker: 'Petrolier',
    productionByOperator: 'Production par Operateur',
    marketShareProduction: 'Part de Marche (Production)',
    pricesByType: 'Prix par Type de Brut (USD/bbl)',
    exportsByDestination: 'Exportations par Destination',
    productionData: 'Donnees de Production',
    exportTable: 'Tableau des Exportations',
    footerText: 'AlphaData - Intelligence du Marche Petrolier Angolais',
    notAvailable: 'N/D',
    report: 'Rapport',
    typeProduction: 'Production',
    typeMarket: 'Marche',
    typeExports: 'Exportations',
    typeRisk: 'Risque',
    typePredictions: 'Previsions',
    typeGeneral: 'General',
    typeReport: 'Rapport',
    // Cover page
    intelligence: 'INTELLIGENCE DU MARCHE PETROLIER',
    aiBadge: 'GENERE PAR IA',
    liveData: 'DONNEES EN TEMPS REEL',
    requestingCompany: 'SOCIETE DEMANDEUSE',
    requestedBy: 'DEMANDE PAR',
    company: 'Societe:',
    nif: 'NIF:',
    sector: 'Secteur:',
    name: 'Nom:',
    role: 'Poste:',
    email: 'Email:',
    confidentialNotice: 'Ce document contient des informations confidentielles. Sa distribution est restreinte aux destinataires autorises.',
    dataSourcesTitle: 'Sources de Donnees et References',
    dataSourcesIntro: 'Ce rapport s\'appuie sur de multiples sources de donnees verifiees et fiables pour garantir la precision et l\'integrite des analyses presentees.',
    reportInfo: 'INFORMATIONS DU RAPPORT',
    titleLabel: 'Titre:',
    method: 'Methode:',
    aiMethod: 'Genere avec Intelligence Artificielle',
    description: 'Description:',
    contact: 'Contact:',
    website: 'Site web:',
    address: 'Adresse:',
    endInfoPage: 'FIN DE LA PAGE INFORMATIVE - DEBUT DU CONTENU DU RAPPORT',
  },
};

export const getReportTranslation = (lang: ReportLang): ReportTranslation => {
  return reportTranslations[lang] || reportTranslations.pt;
};

/** Data sources translated per language */
export const getTranslatedDataSources = (lang: ReportLang) => {
  const t = getReportTranslation(lang);
  return [
    { name: t.dataSource1Name, type: t.official, description: t.dataSource1Desc },
    { name: t.dataSource2Name, type: t.governmental, description: t.dataSource2Desc },
    { name: t.dataSource3Name, type: t.market, description: t.dataSource3Desc },
    { name: t.dataSource4Name, type: t.ai, description: t.dataSource4Desc },
  ];
};

/** Date formatting per language */
export const formatDateForLang = (date: Date, lang: ReportLang): string => {
  const localeMap: Record<ReportLang, string> = { pt: 'pt-AO', en: 'en-GB', fr: 'fr-FR' };
  return date.toLocaleDateString(localeMap[lang], { day: '2-digit', month: 'long', year: 'numeric', hour: '2-digit', minute: '2-digit' });
};

export const formatDateShortForLang = (date: Date, lang: ReportLang): string => {
  const localeMap: Record<ReportLang, string> = { pt: 'pt-AO', en: 'en-GB', fr: 'fr-FR' };
  return date.toLocaleDateString(localeMap[lang], { day: '2-digit', month: 'short', year: 'numeric' }) + ` · ${String(date.getHours()).padStart(2, '0')}:${String(date.getMinutes()).padStart(2, '0')} WAT`;
};
